### ISSUE TITLE
Implement system to ignore files

### ISSUE THREAD

**Issue by Lektonic** [Lektonic/code-pit#10]
Should behave similar to .gitignore

## Tasks:
- [ ] Finish #9
- [ ] Create model for ignored files
- [ ] Add database integration
- [ ] Modify `add` command to check if file is ignored
- [ ] Update Documentation of above
