### ISSUE TITLE
Implement basic compression for blobs

### ISSUE THREAD

**Issue by Lektonic** [Lektonic/code-pit#3]
## Tasks:
- [ ] Add basic zlib compression for objects
- [ ] Have objects be compressed with zlib / DEFLATE by default
- [ ] Document the above
